React95/React95

- components/ProgressBar/ProgressBar.jsx
This PR fix the blue progress indicator position.
> Fix bluebar positioning

- .all-contributorsrc
- CONTRIBUTING.md
- README.md
- package-lock.json
- package.json
Add README.md and CONTRIBUTING.md
Closes #6
> #6 readme.md

- .all-contributorsrc
- .eslintrc
- README.md
- package-lock.json
- package.json
Eslint found 208 problems, so will start cleaning those up in a separate PR :)
> #58 set up eslint

- .travis.yml
- package.json
Semantic published the package with the wrong path. This PR fixes this
> Add pkgRoot to semantic release

- README.md
> Update React95 clouds url

- .travis.yml
- package-lock.json
- package.json
> Ci improvements

- CONTRIBUTING.md
- README.md
- components/index.js
- Changes to waffle link to github projects page
- Add example to how import a component
- Update CONTRIBUTING with new instructions
> Update README.md, CONTRIBUTING.md and export components

- .eslintrc
- .gitignore
- components/Modal/Modal.jsx
- components/Tabs/Tabs.jsx
- components/Tabs/Tabs.test.jsx
- package-lock.json
- stories/tabs.stories.js
1. add defaultActiveTab and onChange support for tabs 
2. fix some small errors
> add defaultActiveTab and onChange support for tabs 

- components/Tabs/Tabs.test.jsx
- components/TextArea/TextArea.jsx
- components/TextArea/__snapshots__/TextArea.test.jsx.snap
This change fixes the following issue:
> Fixed clippy's text-area overflow height.

- components/index.js
- stories/tree.stories.js
Exports the Tree component from `components/index.js`.
> Exports Tree component

- .all-contributorsrc
- components/Tree/Node.jsx
This PR:
- Adds @andreloureiro as a contributor
- Adds a `defaultProp` value to `onClick` prop, removes unused image imports
> Add contributor

- packages/core/.storybook/manager-head.html
- packages/core/components/Dropdown/Dropdown.jsx
- packages/core/components/Dropdown/__snapshots__/Dropdown.test.jsx.snap
> [Fix]: rounded dropdown

- packages/core/components/Checkbox/Checkbox.jsx
- packages/core/components/Checkbox/Checkbox.test.jsx
> Fix styles for Checkbox

- CONTRIBUTING.md
Switched to yarn, added info about packages, made some markdown changes.
> `CONTRIBUTING.md` updates

- packages/core/components/Alert/Alert.jsx
- packages/core/components/Alert/__snapshots__/Alert.test.jsx.snap
- packages/core/components/Modal/Modal.jsx
- packages/core/components/Modal/Modal.test.jsx
- packages/core/components/Modal/__snapshots__/Modal.test.jsx.snap
- packages/core/stories/modal.stories.js
- yarn.lock
Also remove `width="auto"` from Alert component.
closes #105
> #105 Changes width and height from Modal

- packages/core/components/Video/Video.jsx
- packages/core/components/Video/Video.test.jsx
- packages/core/components/Video/__snapshots__/Video.test.jsx.snap
- packages/core/components/Video/buttons/Pause.jsx
- packages/core/components/Video/buttons/Play.jsx
- packages/core/components/Video/buttons/Stop.jsx
- packages/core/components/Video/buttons/index.js
This PR includes missing tests for video "ended" event:
> Video "ended" event tests

- README.md
Adding my website that using this wonderful lib ❤️
> Add a project in README.md

- README.md
As suggested by @ggdaltoso here https://github.com/React95/React95/issues/148#issuecomment-639429610
> Add my personal website to awesome projects section

- README.md
As @ggdaltoso  suggeted in https://github.com/React95/React95/issues/148#issuecomment-639429610
> Added personal website to README

- packages/core/stories/icons.stories.js
> fix(icons.stories): keyed icon sizes by icon name

- README.md
Recently I create a new personal site using React95. This PR update repo in README.
> Update repository in projects

- packages/core/components/TaskBar/TaskBar.tsx
- packages/core/components/TaskBar/WindowButton.tsx
- packages/core/components/TaskBar/__snapshots__/TaskBar.snap
> Fix wrong icons when Modal is open

- packages/core/components/TaskBar/TaskBar.tsx
- packages/core/components/TaskBar/WindowButton.tsx
- packages/core/components/TaskBar/__snapshots__/TaskBar.snap
fix #203
https://user-images.githubusercontent.com/6536985/103939115-0af0ad00-510a-11eb-823c-dd13a3ca2de0.mp4
> fix TaskBar buttons

- scripts/publish
add prerelease tag when on alpha branch
> ci(actions): create publish script

- packages/core/components/Alert/__snapshots__/Alert.snap
- packages/core/components/Modal/Modal.tsx
- packages/core/components/Modal/__snapshots__/Modal.snap
- packages/core/components/TaskBar/__snapshots__/TaskBar.snap
- scripts/publish
> Fix Modal onClose

- .github/workflows/build_and_publish.yml
- .gitignore
- package.json
- packages/core/package.json
- yarn.lock
This PR adds Bojagi into our CI updating what we have here:
[![95Bojagi](https://user-images.githubusercontent.com/6536985/107639411-956b8580-6c4f-11eb-8dc2-d7dca9782720.jpg)](https://bojagi.io/app/github/react95/React95)
*_image link_
Bojagi is an amazing tool that will help us to keep our components beautiful.
@janneilkka Take a look. I think you will like it!
@sime @tchock @JohannesMerz
Thanks for all your support, guys!
🎉
> Add Bojagi to React95

- lerna.json
- packages/core/package.json
Adds a "types" declaration to the package.json file so TS projects with this as a dependency can find the type declarations
> Add "types" declaration to package.json

- .github/workflows/bojagi-upload.yml
> Forward command line args

- .github/labeler.yml
- .github/workflows/labeler.yml
> Add pull request labeler

- packages/core/components/TaskBar/__snapshots__/TaskBar.snap
> test(TaskBar): update TaskBar snapshot

- .codesandbox/ci.json
- .husky/pre-commit
- .husky/pre-push
- package.json
- yarn.lock
from v4 to v7
Give me back my hooks! 😂
> Updating husky

- .github/FUNDING.yml
> Updating FUNDING.yml

- .github/FUNDING.yml
changing myself to React95 organization
> Updating FUNDING.yml 

- .github/FUNDING.yml
> Updating FUNDING.yml [skip ci]

- packages/core/components/Video/Video.test.tsx
- packages/core/components/Video/Video.tsx
- packages/core/components/Video/__snapshots__/Video.snap
- packages/core/components/Video/buttons/Fullscreen.tsx
- packages/core/components/Video/buttons/index.ts
Was created a button to full screen in Video component
#288
> Add resource from full screen

- .all-contributorsrc
- README.md
The reason for this PR is to fix the all-contributors in README.md
> Fix all-contributors on README.md

- lerna.json
- package.json
- packages/core/package.json
Also, skipping @react95/explorer package for being building and published
> Updating storybook CLI configuration

- .github/labeler.yml
- .github/workflows/labeler.yml
- packages/gatsby-theme/README.md
- packages/gatsby-theme/gatsby-node.js
- packages/gatsby-theme/src/components/content-explorer.js
- packages/gatsby-theme/src/components/content.js
- packages/gatsby-theme/src/components/taskbar.js
Now you can add a `modal` boolean property, in your frontmatter, to conditional render your content inside [@React95 Modal](https://react95.github.io/React95/?path=/story/modal--simple) (defaults `true`)
This PR also is adding a new frontmatter prop to be used as a prop inside any MDX 
for example:
```mdx
---
title: Hello World (example)
image: /some-image.jpg
icon:
name: Computer
variant: 32x32_4
---
<pre>
{JSON.stringify(props.frontmatter, null, 2)}
</pre>
```
> Gatsby-theme: Modal opt-out

- LICENSE
- README.md
updated LICENCE and README.md with the comment, "Windows and all associated images are the property of the Microsoft Corp and are not covered by this license."
this come from #313 .
> docs: update LICENCE and README.md

- packages/clippy/src/ClippyProvider.jsx
fix(clippy): add s3 CDN and conditionally set clippy cdn variable based on the window property
fix #319
> Add s3 CDN and conditionally set clippy cdn variable based on the window property

- packages/core/components/Input/Input.tsx
- packages/core/components/Input/__snapshots__/Input.snap
- packages/core/components/TaskBar/__snapshots__/TaskBar.snap
- packages/core/components/TextArea/TextArea.tsx
- packages/core/components/TextArea/__snapshots__/TextArea.snap
> fix(input): update border-radius on iOS

- .codesandbox/ci.json
- .github/workflows/build_and_publish.yml
- .github/workflows/check-pr.yml
> Create check-pr Action

- README.md
removes this https://tominasweb.com from readme
i highly recommend testing the link. i get redirects so various ads and malicous content
> remove one personal portfolio website (spam link)

- .github/workflows/nx.yml
changing from `pull_request` to `pull_request_target`
> ci: updating nx

- lerna.json
- package.json
- yarn.lock
> chore: update to Nx

- .github/workflows/build_and_publish.yml
- the workflow use GH_TOKEN instead
> chore: remove content permission

- .nxignore
- README.md
I built a website for Ideal Labs using react95 and want to include it in the awesome projects section. If it doesn't meet the conditions to make the list, that's ok too.
> Add Ideal Labs to awesome projects

- README.md
It's an honor to do the PR for the awesome projects. Until last year, I didn't know how to program in React, and now here I am making this PR
> docs: add my website to awesome projects

- packages/core/package.json
- packages/core/vite-plugin-css-import-inject.js
- packages/core/vite.config.js
> build: better support for ES modules

- packages/core/vite-plugin-css-import-inject.js
- packages/core/vite.config.js
now with `cjs` extension
bump alpha.5 -> alpha.v6
> build: better support for Common JS

- packages/core/tsconfig.production.json
- packages/core/tsconfig.themes.json
> build: fix `@types` folder path

- packages/core/package.json
- packages/core/tsconfig.production.json
- packages/core/tsconfig.themes.json
> build: types output folder without `@`

- scripts/prepublish.js
> fix: generating `types` folder instead of `@types`

- packages/core/README.md
This commit updates the document to clarify two problems that have been troubling me for a long time, as mentioned in #444, #445.
I believe that providing clear explanations and examples here can help more people to use the ```8.0.0``` version of this component library correctly and avoid making the same mistake as me.
> docs: update /package/core/README.md to add some useful notes

- packages/core/package.json
> revert(core): reverting exports order

- .github/workflows/build_and_publish.yml
missing node version bump on the build file
> ci: update node version for build and publish action

- README.md
- packages/core/components/Dropdown/Dropdown.tsx
This is my first ever pull request so let me know if there's any mistakes! I'll gladly fix them :) 
I added a line to the dropdown menu to be able to change the size of it, that i got help to do [here.](https://github.com/React95/React95/discussions/463#discussioncomment-10753154)
And I also added my [portfolio](https://hawwokitty.github.io/my-portfolio/) that I'm currently working on, it's still a WIP, but the link will stay the same!
> Edit to dropdown menu & added to "Awesome projects"

- README.md
- packages/core/components/Alert/__snapshots__/Alert.snap
- packages/core/components/Modal/Modal.css.ts
- packages/core/components/Modal/Modal.test.tsx
- packages/core/components/Modal/Modal.tsx
- packages/core/components/Modal/__snapshots__/Modal.snap
- packages/core/components/TaskBar/TaskBar.tsx
- packages/core/components/TaskBar/__snapshots__/TaskBar.snap
- packages/core/components/TitleBar/TitleBar.tsx
- packages/core/components/shared/events.ts
- packages/core/stories/modal.stories.css.ts
- packages/core/stories/modal.stories.tsx
- packages/core/stories/taskbar.stories.tsx
This update adds a minimize modal/window function if you use <Modal.Minimize />.
> Adding minimize button feature

- packages/core/components/Alert/__snapshots__/Alert.snap
- packages/core/components/Avatar/__snapshots__/Avatar.snap
- packages/core/components/Frame/Frame.css.ts
- packages/core/components/Modal/__snapshots__/Modal.snap
- packages/core/components/ProgressBar/__snapshots__/ProgressBar.snap
- packages/core/components/TaskBar/__snapshots__/TaskBar.snap
- packages/core/components/Video/__snapshots__/Video.snap
- packages/core/stories/frame.stories.tsx
New extended API:
```tsx
<Frame w="$20" h="$10" padding="$4">
Using design tokens
</Frame>
<Frame w="200px" h="100px" padding="16px">
Using CSS values
</Frame>
<Frame w={{ mobile: '100%', tablet: '50%', desktop: '$20' }}>
Responsive content with mixed tokens and CSS values
</Frame>
```
This pull request introduces responsive design updates to multiple components by adding mobile-specific styles and conditions. The changes ensure that components adapt to different screen sizes, enhancing usability on mobile devices. Key updates include modifications to snapshot files for `Alert`, `Avatar`, `Modal`, `ProgressBar`, and `TaskBar`, as well as updates to the `Frame.css.ts` file to define responsive conditions.
* [`packages/core/components/Frame/Frame.css.ts`](diffhunk://#diff-168e2d353e1c35b8231 …
> Frame is now responsive!
