- README.md
- components/Button/index.js
- components/index.js
- package-lock.json
- package.json
This PR:
- Moves `styled-components` from `dependencies` to `devDependencies` and `peerDependencies`;
- Adds `react` and `react-dom` as peer dependencies;
- Fixes the imports from the import aggregator `components/index.js`;
- Removes the file extension from the import on `components/Button/index.js` - after building, `Button.jsx` becomes `Button.js`, thus the `Button` component was broken when imported in an app;
- Updates README;
> Fix imports exports

- stories/modal.stories.js
just a small typo when copying the code to use as example.
> docs(modal): fix typo in code const

- components/RadioButton/RadioButton.jsx
- components/RadioButton/RadioButton.test.jsx
- components/RadioButton/__snapshots__/RadioButton.test.jsx.snap
PR to close the #111 issue
According to css rules: pseudo-classes applied together should be chained.  
Using construction similar to: `&:checked &:disabled` caused creation of two separate CSS rules and I can't say what exact state will led them to being applied. 
My proposal is to just compress rule to `&:checked:disabled` so it can work.
Screenshot: 
I've also updated snapshots just-in-case and upgraded test the same way. Unfortunately, found no way to test whether two snapshots match each other (to check if `:checked:disabled` order makes changes).
You can see in `components/RadioButton/__snapshots__/RadioButton.test.jsx.snap` line `262` (of my proposed file), that classes seem to render correctly.
> Bugfix: fix radiobutton checked disabled

- packages/icons/package.json
Remove the `directories` and `files` fields from `package.json` and adds `directory: "dist"` inside `publishConfig`.
This way the CI will publish the correct directory.
> Fix icons package.json

- packages/core/components/Alert/__snapshots__/Alert.snap
- packages/core/components/Modal/Modal.test.tsx
- packages/core/components/Modal/Modal.tsx
- packages/core/components/Modal/__snapshots__/Modal.snap
- packages/core/components/Tabs/__snapshots__/Tabs.snap
- packages/core/components/TaskBar/__snapshots__/TaskBar.snap
- packages/core/components/Tooltip/__snapshots__/Tooltip.snap
- packages/core/components/Video/__snapshots__/Video.snap
Options Box list does not contain `<li>` and this is a tech debt because screen readers and other assistive technologies depend on lists being structured properly to keep users informed of content within the lists.
This PR fixes this by adding a li (named `OptionItem`) in OptionsBox.
Reference: https://web.dev/list/
_Obs: If this PR is able to participate in Hacktoberfest, add the label `hacktoberfest-accepted` to count in my contributions :)_
> Modal: Add <li> in OptionsBox

- packages/clippy/src/ClippyProvider.jsx
> fix: remove s3 CDN and use default github CDN to allow NextJS SSR

- packages/core/components/GlobalStyle/GlobalStyle.tsx
Hi!
While testing setting up [bojagi](https://bojagi.io) in your project we noticed some fonts erroring out. This pr should hopefully fix those.
Bug:
double extension in styles for eot fonts (`...eot.eot?#iefix` instead of `...eot?#iefix`).
> fix(core): use eot fonts in global styles correctly

- packages/core/components/Alert/Alert.tsx
- packages/core/components/Modal/Modal.tsx
- packages/core/components/Modal/ModalContext.ts
- packages/core/components/TaskBar/TaskBar.tsx
Fixes https://github.com/React95/React95/issues/155
This adds an extra `hasWindowButton` prop to the Modal component. ✨
> fix: prevent Alert to be displayed in TaskBar as a WindowsButton

- package.json
- yarn.lock
Bojagi CLI v0.13.x uses deprecated APIs.
Good news is CLI v0.15.x is faster :)
> chore: Bojagi CLI upgrade

- .github/workflows/bojagi.yml
Until now Bojagi was just running on master and alpha branches.
To really take the most out of it it should run on every commit so you can review PR changes.
I made a separate job that only builds Bojagi without any branch restrictions and removed it from the build and deploy job.
> chore: Make Bojagi run on every commit/branch

- package.json
- packages/core/package.json
- packages/icons/babel.config.js
Just an experiment that can be true, if it fits well
This PR adds a babel plugin to transforms PNG files into base64 making @react95/icons work without any loader
> Fix icons assets

- packages/icons/package.json
- packages/icons/processIcons.ts
Fixes the bug where png files weren't available in the bundle since they weren't copied into the
dist folder
fix #259 #253
> fix(icons): add postbuild copy command to move png files into dist

- packages/core/components/Modal/Modal.test.tsx
- packages/core/components/Modal/Modal.tsx
- packages/core/components/Modal/ModalContext.ts
- packages/core/components/Modal/ModalProvider.tsx
- packages/core/components/TaskBar/TaskBar.tsx
- packages/core/package.json
- yarn.lock
Makes the ModalProvider state update as required for modal titles and icons to be updated in the
taskbar if they're changed in the modals.
Also fixes the bug that would remove all instances of a modal with the same title when one is removed.
IDs were added to the modals, and used to reference removal and/or update of modals. For backwards compatibility, if anyone's using the modal provider directly, I've kept the current method for removing modals as-is
fixes: #231
> fix(modal): update taskbar icon and text on modal change

- packages/core/components/TaskBar/TaskBar.tsx
The lighthouse reports an error on the SEO topic because the logo in TaskBar doesn't have `alt` attribute. This PR fixes it.
> fix(TaskBar): add alt attribute in logo

- packages/core/components/Modal/Modal.tsx
- packages/core/stories/modal.stories.tsx
Existing code doesn't activate modal until user releases their mouse click. This causes the modal
dragging to be behind the currently active modal. This fix/feature immediately activates the modal
window on click, allowing it to drag in front of all other modals.
* Also adds a "Multiple" story to the Modal section of Storybook, demonstrating how the changes work
> feat(modal): instant activation of modal on click rather than on mouseUp

- .all-contributorsrc
Replace my profile URL from the personal website to the GitHub profile.
> chore: update LRNZ09 profile url

- packages/gatsby-theme/package.json
Fixes https://github.com/React95/React95/issues/351
Fixes with latest version of gatsby
> Update react95/core peerdependencies to 6.0.4 on gastby-theme

- packages/clippy/src/ClippyProvider.jsx
Currently, Clippy is broken on every page using this package, because the referenced S3 Bucket has been deleted. Unfortunately, there is also no way to overwrite the CDN URL from the outside to fix this issue directly.
My proposed change addresses both of these situations:
* By passing the `baseUrl` into the `clippy.load` function, we avoid declaring the unnecessary global parameter. I have updated the default value to the gitcdn value that the author of the npm package uses itself.
* By using the `||` or, we allow any page to declare their own path by specifying `window.CLIPPY_CDN` themselves.
> fix(clippy): broken dependecy url

- packages/icons/.gitignore
- packages/icons/src/iconDemos.ts
We need to ensure running `process-icons` before `dev` and `build:storybook` scripts.
The `process-icons` is responsible for transforming `.ico` into React components but also for creating a file for exporting each icon and its variants.
> ci(icons): keep `iconDemos.ts`

- packages/clippy/src/ClippyProvider.jsx
The old cdn url resulted in png paths like https://cdn.jsdelivr.net/pi0/clippyjs/master/assets/agents/Clippy/map.png which does not resolve - I guess this is an old jsdelivr URL scheme? The original clippyjs uses gitcdn.xyz which doesn't seem to exist at all.
With this update the png path is https://cdn.jsdelivr.net/gh/pi0/clippyjs@master/assets/agents/Clippy/map.png which is correct.
Docs: https://github.com/jsdelivr/jsdelivr#github
Users can work around this by setting `window.CLIPPY_CDN` manually, but may as well make it work out of the box. (Separate issue - error messages are silently swallowed so this kind of thing is tricky to debug right now).
> fix(jsdelivr): correct CLIPPY_CDN

- packages/core/.storybook/src/theme-changer/register.js
- packages/core/components/Video/Video.test.tsx
- packages/core/components/Video/Video.tsx
- packages/core/package.json
- packages/icons/babel.config.js
- packages/icons/package.json
- packages/icons/tsconfig.json
- tsconfig.json
- yarn.lock
To get #409 fixed, we removed the `onClick` handler from the Video#range and added an `onChange` instead.
I'm also taking advantage of this and fixing some dependencies mismatching.
This PR fix #409
> Updating Video event handlers

- packages/core/package.json
I think I know why this was happening:
| Before | After |
| ------- | ----- |
| <pre lang="json">"./themes/\*.css": { &#13;  "types": "./types/themes/all.d.ts", &#13;  "import": "./esm/themes/\*.css.mjs", &#13;  "require": "./cjs/themes/*.css.cjs" &#13; },&#13;"./GlobalStyle": {&#13;  "import": "./esm/GlobalStyle.mjs", &#13;  "require": "./cjs/GlobalStyle.cjs" &#13;} </pre> | <pre lang="json">"./themes/\*.css": { &#13;  "types": "./types/themes/all.d.ts",&#13;  "import": "./esm/themes/\*.css.ts.vanilla.css",&#13;  "require": "./cjs/themes/*.css.ts.vanilla.css"&#13;},&#13;"./GlobalStyle": {&#13;  "import": "./esm/GlobalStyle/GlobalStyle.css.ts.vanilla.css",&#13;  "require": "./cjs/GlobalStyle/GlobalStyle.css.ts.vanilla.css"&#13;}</pre> |
So, as you can see, the before column targets the …
> fix(core): `GlobalStyle` and `themes` are missing after build

- packages/core/package.json
So this syntax works too
```js
import { Button } from '@react95/core/Button';
import { Cursor } from '@react95/core/Cursor';
import { List } from '@react95/core/List';
import { TaskBar } from '@react95/core/TaskBar';
```
And this will keep working 
```js
import { Button, Cursor, List, TaskBar } from '@react95/core';
```
> feat: Exporting each component in `exports` field

- package.json
- packages/clippy/package.json
- packages/clippy/tsconfig.cjs.json
- packages/clippy/tsconfig.esm.json
- packages/clippy/vite.config.js
- packages/core/package.json
- packages/core/vite.config.js
- yarn.lock
Clippy isn't working. This PR fixes it 🩹 
To give more context, our `@react95/clippy` has been using [clippyts](https://github.com/lizozom/clippyts) since #452 but it was not working because `clippyts` will do a [dynamic import to choose which agent it will display](https://github.com/lizozom/clippyts/blob/master/src/agents/index.ts#L3-L11) and the build steps weren't prepared for such convenience.
Now, powered by Vite, we're prepared!
> fix(clippy): building clippy with vite

- packages/core/components/List/List.css.ts
I noticed this bug when talking to @janneilkka. And here is the fix 🚀 
| Before | After |
| ------- | ----- |
| ![image](https://github.com/user-attachments/assets/85d67666-452e-4014-bbe5-54620edd68b9) | ![image](https://github.com/user-attachments/assets/6ba80725-1d6f-4d80-923e-c14ebd8118f3) |
> fix: list item background color on hover

- packages/core/components/Avatar/Avatar.tsx
- packages/core/components/Checkbox/Checkbox.tsx
- packages/core/components/Fieldset/Fieldset.tsx
- packages/core/components/Input/Input.tsx
- packages/core/components/RadioButton/RadioButton.tsx
- packages/core/components/Tabs/Tab.tsx
- packages/core/components/TaskBar/TaskBar.tsx
- packages/core/components/TextArea/TextArea.tsx
- packages/core/components/Tree/Node.tsx
- packages/core/components/Tree/Tree.tsx
This pull request introduces a consistent approach to handling `className` props across multiple components in the `packages/core/components` directory by integrating the `classnames` library. This change simplifies the merging of class names and enhances flexibility for component styling.
* **Avatar Component**: Added `className` support by merging it with existing styles using `classnames` in the `Avatar` component. (`packages/core/components/Avatar/Avatar.tsx`) [[1]](diffhunk://#diff-4baf7847d1d7edc923cfd97a441e930ad28c022c410777f5309462df550eee33R12) [[2]](diffhunk://#diff-4baf7847d1d7edc923cfd97a441e930ad28c022c410777f5309462df550eee33L23-R41)
* **Checkbox Component**: Incorporated `classnames` to merge `className` with default styles in the `Checkbox` component. …
> Feat: extending `className` on missing components

- packages/core/package.json
Updated the types path for the contract entry in package.json from "./types/themes/contract.d.ts" to "./types/themes/contract.css.d.ts" to ensure proper type definitions are referenced.
> fix: correct types path for `contract` in `package.json`

- packages/core/components/Modal/Modal.tsx
- packages/core/components/TitleBar/TitleBar.tsx
- packages/core/stories/titlebar.stories.tsx
This pull request refactors the `TitleBar` component in `TitleBar.tsx` to improve its type safety and flexibility, especially around polymorphic `as` props and TypeScript generics. The most important changes include updating type definitions for props, refactoring the renderer to support polymorphic elements, and cleaning up legacy type usage.
* Refactored `TitleBarBackgroundProps` and `TitleBarProps` to be generic over `ElementType`, enabling the `TitleBar` component to be used with different HTML elements via the `as` prop.
* Updated the `TitleBarRenderer` function to use generic types and `ElementRef<TAs>`, improving type safety for refs and props.
* Removed legacy interface definitions and the use of `ForwardRefRenderFunction` in favor of more flexible generic types. …
> fix: update TitleBar type to extend `as` prop
